services:
  postgres-db:
      image: postgres:15-alpine
      environment:
        - POSTGRES_USER=minitwit_admin
        - POSTGRES_PASSWORD=dev_password
        - POSTGRES_DB=minitwit
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U minitwit_admin -d minitwit"]
        interval: 2s
        timeout: 5s
        retries: 5

  java-backend:
    build: ./minitwit-java
    ports:
      - "7070:7070"
      - "5005:5005" # Open port for debugging
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 # For attaching VSCode debugger
      - JDBC_URL=jdbc:postgresql://postgres-db:5432/minitwit
      - JDBC_USER=minitwit_admin
      - JDBC_PASS=dev_password
    depends_on:
      postgres-db:
          condition: service_healthy

  svelte-frontend:
    build:
      context: ./minitwit-svelte
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./minitwit-svelte:/app
      - /app/node_modules
      - /app/.svelte-kit
    command: npm run dev -- --host 0.0.0.0  
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1 # Enable polling to make hot reload work for Svelte
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - java-backend

  prometheus:
    build:
      context: ./monitoring/prometheus
      dockerfile: Dockerfile
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - java-backend

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  prometheus_data: 
  grafana_data: